### ISSUE TITLE
How to run the code FedAVG-CDP in cifar10 without privateFL

### ISSUE THREAD

**Issue by outouser** [BHui97/PrivateFL#1]
Hi,Thanks to the author for the code，I want to reproduce the code without privateFL in the same scene, but there seems to be privateFL in the script, what should I do?

**Comment by outouser** [comment]
Hello, I have another question. According to the modelUtil.py file, when evaluating the global model during evaluate_global, the code uses various clients to assess the global model. Why not use the server model to evaluate the global model?

**Comment by outouser** [comment]
Hello, I have another question about testing accuracy of the global model, according to line 104 of the file FedAverage.py, acc = evaluate_global(users, test_dataloaders, range(NUM_CLIENTS)). Why is the testing accuracy of the global model calculated using each client model instead of the server or global model?

**Comment by BHui97** [comment]
You can modify the argument of code in script. If you would like to run the code without privateFl, you can modify the argument , 'model' without IN, e.g. changing the 'resnet18_IN' to 'resnet18'. 
For the second question, we have a personalized transformation for each client. Thus, we calculate the accuracy at each client. In real world scenario, the global model is distributed to each client and do the prediction tasks.

**Comment by outouser** [comment]
Glad to receive your response. Thank you for your assistance.
